from datetime import datetime
from sqlalchemy import Boolean, Float, DateTime, Integer, String, Text, func
from sqlalchemy.orm import Mapped, mapped_column

from app.models.base import Base


class Report(Base):
    """Community-submitted disaster report, analyzed by IndoBERT."""

    __tablename__ = "reports"

    id: Mapped[int] = mapped_column(primary_key=True, autoincrement=True)
    lat: Mapped[float] = mapped_column(Float, nullable=False, index=True)
    lng: Mapped[float] = mapped_column(Float, nullable=False, index=True)

    text: Mapped[str] = mapped_column(Text, nullable=False)

    # e.g. "Banjir", "Longsor", "Gempa", "Kebakaran", "Lainnya"
    category: Mapped[str] = mapped_column(String(50), default="Lainnya")

    # Optional image uploaded to Firebase Storage
    image_url: Mapped[str] = mapped_column(String(500), nullable=True)

    # IndoBERT verification output
    verified: Mapped[bool] = mapped_column(Boolean, default=False)
    verification_score: Mapped[float] = mapped_column(Float, default=0.0)

    # Source: "user" | "petabencana"
    source: Mapped[str] = mapped_column(String(50), default="user")

    # Anonymous device identity — UUID generated by the Android app on first install
    device_id: Mapped[str] = mapped_column(String(128), nullable=False, default="", index=True)

    # Anti-spam: community flagging
    flag_count: Mapped[int] = mapped_column(Integer, default=0)
    # Hidden when flag_count >= 3; admin can restore by setting visible=True
    visible: Mapped[bool] = mapped_column(Boolean, default=True)

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), index=True
    )
